# 📋Table of Contents
* INtroduction
* 📚 Import Libraries
* 📖 Read Dataset
* 😅😅Missing Values
* 🖇🖇📭Data Pipeline
* ⚙️Finding and Training Models With Best Hyperparameters
* 👀👁FInal MOdel WIth VOting
* 📊Generate Predictions and Create Submission File

# INtroduction

**Hi , you clicked this notebook, so without any wasting time, let's get started, but some context, this is multiclass prediction model, which has predict the probabilities of the classes of the columns, and submit them into csv file. Hope you will play with it , plz don't forget mention this notebook , if you 're building the model on the top of this notebook**

# 📚Import Libraries

In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import warnings
import optuna
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingClassifier
from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import log_loss, make_scorer
from sklearn.ensemble import VotingClassifier


warnings.filterwarnings("ignore")

# 📖Read Dataset

In [2]:
train = pd.read_csv('/kaggle/input/playground-series-s3e26/train.csv')
main = pd.read_csv('/kaggle/input/cirrhosis-patient-survival-prediction/cirrhosis.csv')
test = pd.read_csv('/kaggle/input/playground-series-s3e26/test.csv')

In [3]:
main.rename(columns ={'ID':'id'}, inplace = True)
print(main.shape, train.shape)
train = pd.concat([train, main], axis = 0)

(418, 20) (7905, 20)

In [4]:
train.describe().T

,count,mean,std,min,25%,50%,75%,max
id,8323.0,3764.043133,2369.682885,0.00,1662.50,3743.00,5823.50,7904.00
N_Days,8323.0,2024.528776,1094.968696,41.00,1220.00,1831.00,2689.00,4795.00
Age,8323.0,18381.192359,3686.832308,9598.00,15574.00,18713.00,20684.00,28650.00
Bilirubin,8323.0,2.625940,3.847146,0.30,0.70,1.10,3.00,28.00
Cholesterol,8189.0,351.219074,196.775246,120.00,248.00,299.00,392.00,1775.00
Albumin,8323.0,3.545767,0.350697,1.96,3.35,3.58,3.77,4.64
Copper,8215.0,84.421546,76.327480,4.00,39.00,63.00,102.00,588.00
Alk_Phos,8217.0,1823.044883,1913.388685,289.00,834.00,1181.00,1857.00,13862.40
SGOT,8217.0,114.906530,49.134067,26.35,75.95,108.50,137.95,457.25
Tryglicerides,8187.0,115.662636,53.037660,33.00,84.00,104.00,139.00,598.00
Platelets,8312.0,264.827238,88.039809,62.00,210.00,264.00,316.00,721.00
Prothrombin,8321.0,10.634575,0.795707,9.00,10.00,10.60,11.00,18.00
Stage,8317.0,3.032103,0.867235,1.00,2.00,3.00,4.00,4.00

# 😅😅Missing Values

In [5]:
print(train.isnull().sum())
test.isnull().sum()

id                 0
N_Days             0
Drug             106
Age                0
Sex                0
Ascites          106
Hepatomegaly     106
Spiders          106
Edema              0
Bilirubin          0
Cholesterol      134
Albumin            0
Copper           108
Alk_Phos         106
SGOT             106
Tryglicerides    136
Platelets         11
Prothrombin        2
Stage              6
Status             0
dtype: int64

id               0
N_Days           0
Drug             0
Age              0
Sex              0
Ascites          0
Hepatomegaly     0
Spiders          0
Edema            0
Bilirubin        0
Cholesterol      0
Albumin          0
Copper           0
Alk_Phos         0
SGOT             0
Tryglicerides    0
Platelets        0
Prothrombin      0
Stage            0
dtype: int64

**Wow that's miracle there's no missing values yipee!!**

In [6]:
# One-hot encode the target variable

y = train['Status']
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)

X = train.drop(['id', 'Status'], axis=1)
test = test.drop(['id'], axis=1)

In [7]:
num = X.select_dtypes(include=['int64', 'float64']).columns
col = X.select_dtypes(include=['object']).columns

# 🖇🖇📭Data Pipeline

In [8]:
# Preprocessing for numerical data: imputation and scaling
numerical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())])

# Preprocessing for categorical data: imputation and one-hot encoding
categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder(handle_unknown='ignore'))])

preprocessor = ColumnTransformer(
    transformers=[
        ('num', numerical_transformer, num),
        ('cat', categorical_transformer, col)])

In [9]:
# Split data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# ⚙️Finding  and Training  Models With Best Hyperparameters

In [10]:
#Best for XBG

# Define the objective function for Optuna
# def objective(trial):

#     params = {
#         'objective': 'multi:softprob',
#         'max_depth': trial.suggest_int('max_depth', 3, 100),
#         'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.3),
#         'n_estimators': trial.suggest_int('n_estimators', 50, 1000, step=10),
#         'subsample': trial.suggest_float('subsample', 0.5, 1.0),
#         'colsample_bytree': trial.suggest_float('colsample_bytree', 0.1, 1.0),
#         'gamma': trial.suggest_float('gamma', 0, 1),
#         'booster': trial.suggest_categorical('booster', ['gbtree', 'gblinear', 'dart']),

#     }
#     model = XGBClassifier(**params)
    
#     # Create the full pipeline with the preprocessor
#     pipeline = Pipeline(steps=[('preprocessor', preprocessor), ('model', model)])

#     # Train the model
#     pipeline.fit(X_train, y_train)

#     # Make predictions
#     y_pred_proba = pipeline.predict_proba(X_test)

#     # Calculate log loss
#     loss = log_loss(y_test, y_pred_proba)
#     return loss

# # Perform hyperparameter optimization
# study = optuna.create_study(direction='minimize')
# study.optimize(objective, n_trials=1500)

# # Print the best hyperparameters and corresponding accuracy
# best_trial = study.best_trial
# print(f"Best Trial - Hyperparameters: {best_trial.params}")
# print(f"Best Trial - Accuracy: {best_trial.value}")

In [11]:
model = XGBClassifier(**{'objective': 'multi:softprob','max_depth': 29, 'learning_rate': 0.044754600706634465, 'n_estimators': 850, 'subsample': 0.6529370752777335, 'colsample_bytree': 0.17930720266844047, 'gamma': 0.8811229412407853, 'booster': 'gbtree'})

XBG_pipeline = Pipeline(steps=[('preprocessor', preprocessor), ('model', model)])

In [12]:
# Best for LGBM
# # Define the objective function for Optuna
# def objective(trial):

#     params = {
#             'objective': 'multiclass',
#             'metric': 'softmax',
#             'boosting_type': 'gbdt',
#             'num_leaves': trial.suggest_int('num_leaves', 2, 256),
#             'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.3),
#             'n_estimators': trial.suggest_int('n_estimators', 100, 1000, step=100),
#             'subsample': trial.suggest_float('subsample', 0.5, 1.0),
#             'colsample_bytree': trial.suggest_float('colsample_bytree', 0.5, 1.0),
#             'reg_alpha': trial.suggest_float('reg_alpha', 0, 1),
#             'reg_lambda': trial.suggest_float('reg_lambda', 0, 1),
#         }
#     model = LGBMClassifier(**params)
    
#     # Create the full pipeline with the preprocessor
#     pipeline = Pipeline(steps=[('preprocessor', preprocessor), ('model', model)])

#     # Train the model
#     pipeline.fit(X_train, y_train)

#     # Make predictions
#     y_pred_proba = pipeline.predict_proba(X_test)

#     # Calculate log loss
#     loss = log_loss(y_test, y_pred_proba)
#     return loss

# # Perform hyperparameter optimization
# study = optuna.create_study(direction='minimize')
# study.optimize(objective, n_trials=1500)

# # Print the best hyperparameters and corresponding accuracy
# best_trial = study.best_trial
# print(f"Best Trial - Hyperparameters: {best_trial.params}")
# print(f"Best Trial - Accuracy: {best_trial.value}")

In [13]:
model = LGBMClassifier(**{'objective': 'multiclass','metric': 'softmax',
                        'boosting_type': 'gbdt','num_leaves': 13, 'learning_rate': 0.040717487378551125, 'n_estimators': 340, 
                          'subsample': 0.7621117946415148, 'colsample_bytree': 0.5254951985706161, 'reg_alpha': 0.9395639914591739, 'reg_lambda': 0.12423847695048462})

LGBM_pipeline = Pipeline(steps=[('preprocessor', preprocessor), ('model', model)])

In [14]:
# Best for CatboostClassifier
# # Define the objective function for Optuna
# def objective(trial):
#     model_params = {
#         'iterations': trial.suggest_int('iterations', 100, 1000, step=10),
#         'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.3),
#         'depth': trial.suggest_int('depth', 3, 10),
#         'subsample': trial.suggest_float('subsample', 0.5, 1.0),
#         'colsample_bylevel': trial.suggest_float('colsample_bylevel', 0.5, 1.0),
#         'bootstrap_type': 'Bayesian',
#         'verbose': False
#     }
#     # Exclude 'subsample' when using 'bayesian' bootstrap type
#     if model_params['bootstrap_type'] == 'Bayesian':
#         del model_params['subsample']
    
#     model = CatBoostClassifier(**model_params)
    
#     # Create the full pipeline with the preprocessor
#     pipeline = Pipeline(steps=[('preprocessor', preprocessor), ('model', model)])

#     # Train the model
#     pipeline.fit(X_train, y_train)

#     # Make predictions
#     y_pred_proba = pipeline.predict_proba(X_test)

#     # Calculate log loss
#     loss = log_loss(y_test, y_pred_proba)
#     return loss

# # Perform hyperparameter optimization
# study = optuna.create_study(direction='minimize')
# study.optimize(objective, n_trials=150)

# # Print the best hyperparameters and corresponding accuracy
# best_trial = study.best_trial
# print(f"Best Trial - Hyperparameters: {best_trial.params}")
# print(f"Best Trial - Loss: {best_trial.value}")

In [15]:
model = CatBoostClassifier(**{'iterations': 860, 'learning_rate': 0.07693815312911455, 'depth': 3, 'subsample': 0.5592260503739381, 
                               'colsample_bylevel': 0.6756953610569407, 'bootstrap_type': 'Bernoulli', 'grow_policy': 'Depthwise',
                               'min_child_samples': 17, 'reg_lambda': 0.39267373457724253})

Cat_pipeline = Pipeline(steps=[('preprocessor', preprocessor), ('model', model)])

In [16]:
# Best for GradientBoosting
    
# # Define the objective function for Optuna
# def objective(trial):

#     params = {
#             'loss': 'deviance',
#             'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.3),
#             'n_estimators': trial.suggest_int('n_estimators', 100, 1000, step=100),
#             'subsample': trial.suggest_float('subsample', 0.5, 1.0),
#             'max_depth': trial.suggest_int('max_depth', 3, 10),
#         }
    
#     model = GradientBoostingClassifier(**params)
    
#     # Create the full pipeline with the preprocessor
#     pipeline = Pipeline(steps=[('preprocessor', preprocessor), ('model', model)])

#     # Train the model
#     pipeline.fit(X_train, y_train)

#     # Make predictions
#     y_pred_proba = pipeline.predict_proba(X_test)

#     # Calculate log loss
#     loss = log_loss(y_test, y_pred_proba)
#     return loss

# # Perform hyperparameter optimization
# study = optuna.create_study(direction='minimize')
# study.optimize(objective, n_trials=1500)

# # Print the best hyperparameters and corresponding accuracy
# best_trial = study.best_trial

# print(f"Best Trial - Hyperparameters: {best_trial.params}")
# print(f"Best Trial - Accuracy: {best_trial.value}")

In [17]:
model = GradientBoostingClassifier(**{'loss': 'deviance','learning_rate': 0.05885877940951943, 'n_estimators': 300, 'subsample': 0.5470272507158589, 'max_depth': 3})

Gradient_pipeline = Pipeline(steps=[('preprocessor', preprocessor), ('model', model)])

# 👀👁FInal MOdel WIth VOting

In [18]:
# Create a VotingClassifier with the three XGBoost models
voting = VotingClassifier(estimators=[
    ('Model1', XBG_pipeline),
    ('Model2', LGBM_pipeline),
    ('Model3', Cat_pipeline)
], voting='soft')



voting.fit(X, y)

0:	learn: 1.0243593	total: 61.9ms	remaining: 53.2s
1:	learn: 0.9638046	total: 67.1ms	remaining: 28.8s
2:	learn: 0.9120300	total: 71.3ms	remaining: 20.4s
3:	learn: 0.8691257	total: 75.5ms	remaining: 16.2s
4:	learn: 0.8319029	total: 80ms	remaining: 13.7s
5:	learn: 0.7967971	total: 85.1ms	remaining: 12.1s
6:	learn: 0.7666320	total: 89.1ms	remaining: 10.9s
7:	learn: 0.7403344	total: 93.6ms	remaining: 9.97s
8:	learn: 0.7179777	total: 97.6ms	remaining: 9.23s
9:	learn: 0.6982408	total: 102ms	remaining: 8.66s
10:	learn: 0.6795371	total: 106ms	remaining: 8.21s
11:	learn: 0.6625715	total: 111ms	remaining: 7.81s
12:	learn: 0.6475273	total: 115ms	remaining: 7.47s
13:	learn: 0.6338070	total: 119ms	remaining: 7.18s
14:	learn: 0.6222091	total: 123ms	remaining: 6.94s
15:	learn: 0.6103936	total: 128ms	remaining: 6.72s
16:	learn: 0.5993649	total: 133ms	remaining: 6.61s
17:	learn: 0.5899777	total: 138ms	remaining: 6.45s
18:	learn: 0.5820471	total: 142ms	remaining: 6.29s
19:	learn: 0.5749772	total: 146ms	remaining: 6.12s
20:	learn: 0.5686647	total: 150ms	remaining: 5.99s
21:	learn: 0.5620457	total: 154ms	remaining: 5.86s
22:	learn: 0.5564000	total: 158ms	remaining: 5.73s
23:	learn: 0.5507931	total: 162ms	remaining: 5.63s
24:	learn: 0.5464656	total: 166ms	remaining: 5.54s
25:	learn: 0.5420853	total: 170ms	remaining: 5.45s
26:	learn: 0.5380117	total: 174ms	remaining: 5.37s
27:	learn: 0.5340968	total: 178ms	remaining: 5.29s
28:	learn: 0.5305041	total: 182ms	remaining: 5.22s
29:	learn: 0.5267700	total: 187ms	remaining: 5.16s
30:	learn: 0.5238797	total: 191ms	remaining: 5.1s
31:	learn: 0.5212081	total: 195ms	remaining: 5.04s
32:	learn: 0.5189742	total: 199ms	remaining: 4.98s
33:	learn: 0.5164961	total: 203ms	remaining: 4.92s
34:	learn: 0.5139711	total: 207ms	remaining: 4.88s
35:	learn: 0.5112843	total: 211ms	remaining: 4.83s
36:	learn: 0.5091342	total: 215ms	remaining: 4.78s
37:	learn: 0.5070081	total: 219ms	remaining: 4.75s
38:	learn: 0.5050009	total: 224ms	remaining: 4.71s
39:	learn: 0.5034979	total: 228ms	remaining: 4.67s
40:	learn: 0.5022574	total: 232ms	remaining: 4.63s
41:	learn: 0.5006614	total: 236ms	remaining: 4.59s
42:	learn: 0.4992031	total: 240ms	remaining: 4.55s
43:	learn: 0.4979784	total: 244ms	remaining: 4.52s
44:	learn: 0.4967582	total: 248ms	remaining: 4.49s
45:	learn: 0.4948906	total: 252ms	remaining: 4.46s
46:	learn: 0.4937144	total: 257ms	remaining: 4.45s
47:	learn: 0.4924765	total: 263ms	remaining: 4.45s
48:	learn: 0.4912991	total: 267ms	remaining: 4.42s
49:	learn: 0.4897441	total: 272ms	remaining: 4.4s
50:	learn: 0.4881040	total: 276ms	remaining: 4.38s
51:	learn: 0.4870500	total: 280ms	remaining: 4.35s
52:	learn: 0.4856472	total: 284ms	remaining: 4.32s
53:	learn: 0.4845181	total: 288ms	remaining: 4.3s
54:	learn: 0.4833159	total: 293ms	remaining: 4.28s
55:	learn: 0.4820106	total: 297ms	remaining: 4.27s
56:	learn: 0.4812072	total: 302ms	remaining: 4.25s
57:	learn: 0.4798086	total: 306ms	remaining: 4.23s
58:	learn: 0.4793288	total: 310ms	remaining: 4.21s
59:	learn: 0.4781137	total: 314ms	remaining: 4.19s
60:	learn: 0.4772619	total: 319ms	remaining: 4.17s
61:	learn: 0.4766198	total: 323ms	remaining: 4.16s
62:	learn: 0.4761806	total: 327ms	remaining: 4.14s
63:	learn: 0.4753365	total: 332ms	remaining: 4.13s
64:	learn: 0.4745680	total: 336ms	remaining: 4.11s
65:	learn: 0.4741422	total: 341ms	remaining: 4.1s
66:	learn: 0.4736331	total: 345ms	remaining: 4.08s
67:	learn: 0.4728156	total: 349ms	remaining: 4.07s
68:	learn: 0.4721007	total: 354ms	remaining: 4.05s
69:	learn: 0.4713632	total: 358ms	remaining: 4.04s
70:	learn: 0.4702630	total: 362ms	remaining: 4.02s
71:	learn: 0.4697846	total: 368ms	remaining: 4.03s
72:	learn: 0.4689845	total: 373ms	remaining: 4.02s
73:	learn: 0.4686797	total: 377ms	remaining: 4s
74:	learn: 0.4682444	total: 381ms	remaining: 3.99s
75:	learn: 0.4677628	total: 385ms	remaining: 3.98s
76:	learn: 0.4666371	total: 390ms	remaining: 3.96s
77:	learn: 0.4660739	total: 394ms	remaining: 3.95s
78:	learn: 0.4655734	total: 398ms	remaining: 3.94s
79:	learn: 0.4648697	total: 402ms	remaining: 3.92s
80:	learn: 0.4641048	total: 407ms	remaining: 3.91s
81:	learn: 0.4631386	total: 411ms	remaining: 3.9s
82:	learn: 0.4627959	total: 415ms	remaining: 3.88s
83:	learn: 0.4621567	total: 419ms	remaining: 3.87s
84:	learn: 0.4616032	total: 423ms	remaining: 3.86s
85:	learn: 0.4609715	total: 427ms	remaining: 3.85s
86:	learn: 0.4602934	total: 432ms	remaining: 3.83s
87:	learn: 0.4599753	total: 436ms	remaining: 3.82s
88:	learn: 0.4594101	total: 440ms	remaining: 3.81s
89:	learn: 0.4587950	total: 444ms	remaining: 3.8s
90:	learn: 0.4584040	total: 449ms	remaining: 3.79s
91:	learn: 0.4577560	total: 458ms	remaining: 3.83s
92:	learn: 0.4574121	total: 463ms	remaining: 3.82s
93:	learn: 0.4569589	total: 467ms	remaining: 3.81s
94:	learn: 0.4565981	total: 471ms	remaining: 3.79s
95:	learn: 0.4563169	total: 476ms	remaining: 3.79s
96:	learn: 0.4557952	total: 480ms	remaining: 3.78s
97:	learn: 0.4554092	total: 485ms	remaining: 3.77s
98:	learn: 0.4550782	total: 490ms	remaining: 3.76s
99:	learn: 0.4547228	total: 494ms	remaining: 3.75s
100:	learn: 0.4544332	total: 498ms	remaining: 3.74s
101:	learn: 0.4536621	total: 503ms	remaining: 3.73s
102:	learn: 0.4532325	total: 507ms	remaining: 3.73s
103:	learn: 0.4525356	total: 511ms	remaining: 3.72s
104:	learn: 0.4521984	total: 516ms	remaining: 3.71s
105:	learn: 0.4517475	total: 520ms	remaining: 3.7s
106:	learn: 0.4512932	total: 524ms	remaining: 3.69s
107:	learn: 0.4509602	total: 528ms	remaining: 3.68s
108:	learn: 0.4503761	total: 533ms	remaining: 3.67s
109:	learn: 0.4499551	total: 537ms	remaining: 3.66s
110:	learn: 0.4496681	total: 541ms	remaining: 3.65s
111:	learn: 0.4491625	total: 547ms	remaining: 3.65s
112:	learn: 0.4486414	total: 551ms	remaining: 3.65s
113:	learn: 0.4483657	total: 556ms	remaining: 3.64s
114:	learn: 0.4475445	total: 560ms	remaining: 3.63s
115:	learn: 0.4467221	total: 564ms	remaining: 3.62s
116:	learn: 0.4463604	total: 568ms	remaining: 3.61s
117:	learn: 0.4461195	total: 573ms	remaining: 3.6s
118:	learn: 0.4457885	total: 577ms	remaining: 3.59s
119:	learn: 0.4454965	total: 581ms	remaining: 3.58s
120:	learn: 0.4451686	total: 585ms	remaining: 3.57s
121:	learn: 0.4447967	total: 588ms	remaining: 3.56s
122:	learn: 0.4446033	total: 592ms	remaining: 3.55s
123:	learn: 0.4442750	total: 596ms	remaining: 3.54s
124:	learn: 0.4433894	total: 601ms	remaining: 3.53s
125:	learn: 0.4431320	total: 605ms	remaining: 3.52s
126:	learn: 0.4428411	total: 609ms	remaining: 3.51s
127:	learn: 0.4422392	total: 613ms	remaining: 3.5s
128:	learn: 0.4418473	total: 617ms	remaining: 3.5s
129:	learn: 0.4414419	total: 621ms	remaining: 3.49s
130:	learn: 0.4408147	total: 625ms	remaining: 3.48s
131:	learn: 0.4404478	total: 629ms	remaining: 3.47s
132:	learn: 0.4402248	total: 633ms	remaining: 3.46s
133:	learn: 0.4398665	total: 637ms	remaining: 3.45s
134:	learn: 0.4397719	total: 641ms	remaining: 3.44s
135:	learn: 0.4394958	total: 645ms	remaining: 3.43s
136:	learn: 0.4390471	total: 649ms	remaining: 3.42s
137:	learn: 0.4386489	total: 656ms	remaining: 3.43s
138:	learn: 0.4384243	total: 660ms	remaining: 3.42s
139:	learn: 0.4378866	total: 666ms	remaining: 3.42s
140:	learn: 0.4374944	total: 670ms	remaining: 3.42s
141:	learn: 0.4371875	total: 674ms	remaining: 3.41s
142:	learn: 0.4367504	total: 678ms	remaining: 3.4s
143:	learn: 0.4363924	total: 682ms	remaining: 3.39s
144:	learn: 0.4361678	total: 686ms	remaining: 3.38s
145:	learn: 0.4356247	total: 692ms	remaining: 3.38s
146:	learn: 0.4353163	total: 696ms	remaining: 3.37s
147:	learn: 0.4349289	total: 700ms	remaining: 3.37s
148:	learn: 0.4345656	total: 704ms	remaining: 3.36s
149:	learn: 0.4342303	total: 708ms	remaining: 3.35s
150:	learn: 0.4339201	total: 712ms	remaining: 3.34s
151:	learn: 0.4335237	total: 716ms	remaining: 3.33s
152:	learn: 0.4331275	total: 720ms	remaining: 3.33s
153:	learn: 0.4328864	total: 724ms	remaining: 3.32s
154:	learn: 0.4325217	total: 728ms	remaining: 3.31s
155:	learn: 0.4321229	total: 732ms	remaining: 3.3s
156:	learn: 0.4317028	total: 736ms	remaining: 3.3s
157:	learn: 0.4314415	total: 741ms	remaining: 3.29s
158:	learn: 0.4309025	total: 745ms	remaining: 3.28s
159:	learn: 0.4305609	total: 749ms	remaining: 3.28s
160:	learn: 0.4302338	total: 753ms	remaining: 3.27s
161:	learn: 0.4298110	total: 757ms	remaining: 3.26s
162:	learn: 0.4293629	total: 761ms	remaining: 3.25s
163:	learn: 0.4291886	total: 765ms	remaining: 3.25s
164:	learn: 0.4288774	total: 769ms	remaining: 3.24s
165:	learn: 0.4285798	total: 773ms	remaining: 3.23s
166:	learn: 0.4284512	total: 778ms	remaining: 3.23s
167:	learn: 0.4281082	total: 783ms	remaining: 3.22s
168:	learn: 0.4276991	total: 788ms	remaining: 3.22s
169:	learn: 0.4273163	total: 792ms	remaining: 3.21s
170:	learn: 0.4270031	total: 796ms	remaining: 3.21s
171:	learn: 0.4267766	total: 801ms	remaining: 3.2s
172:	learn: 0.4263138	total: 805ms	remaining: 3.2s
173:	learn: 0.4258951	total: 810ms	remaining: 3.19s
174:	learn: 0.4255543	total: 814ms	remaining: 3.18s
175:	learn: 0.4253092	total: 817ms	remaining: 3.18s
176:	learn: 0.4250558	total: 822ms	remaining: 3.17s
177:	learn: 0.4245805	total: 826ms	remaining: 3.17s
178:	learn: 0.4244803	total: 830ms	remaining: 3.16s
179:	learn: 0.4241774	total: 835ms	remaining: 3.15s
180:	learn: 0.4239462	total: 839ms	remaining: 3.15s
181:	learn: 0.4234588	total: 843ms	remaining: 3.14s
182:	learn: 0.4231474	total: 848ms	remaining: 3.13s
183:	learn: 0.4228154	total: 854ms	remaining: 3.14s
184:	learn: 0.4225954	total: 860ms	remaining: 3.14s
185:	learn: 0.4223894	total: 864ms	remaining: 3.13s
186:	learn: 0.4221633	total: 869ms	remaining: 3.13s
187:	learn: 0.4217345	total: 873ms	remaining: 3.12s
188:	learn: 0.4214998	total: 877ms	remaining: 3.12s
189:	learn: 0.4210935	total: 882ms	remaining: 3.11s
190:	learn: 0.4206001	total: 886ms	remaining: 3.1s
191:	learn: 0.4203864	total: 890ms	remaining: 3.1s
192:	learn: 0.4201202	total: 895ms	remaining: 3.09s
193:	learn: 0.4197159	total: 899ms	remaining: 3.09s
194:	learn: 0.4193963	total: 903ms	remaining: 3.08s
195:	learn: 0.4190155	total: 908ms	remaining: 3.07s
196:	learn: 0.4188291	total: 912ms	remaining: 3.07s
197:	learn: 0.4187076	total: 916ms	remaining: 3.06s
198:	learn: 0.4184040	total: 920ms	remaining: 3.06s
199:	learn: 0.4181788	total: 924ms	remaining: 3.05s
200:	learn: 0.4178254	total: 929ms	remaining: 3.04s
201:	learn: 0.4175829	total: 933ms	remaining: 3.04s
202:	learn: 0.4172647	total: 937ms	remaining: 3.03s
203:	learn: 0.4168517	total: 941ms	remaining: 3.02s
204:	learn: 0.4164939	total: 945ms	remaining: 3.02s
205:	learn: 0.4158498	total: 949ms	remaining: 3.01s
206:	learn: 0.4156960	total: 954ms	remaining: 3.01s
207:	learn: 0.4155671	total: 959ms	remaining: 3s
208:	learn: 0.4153381	total: 963ms	remaining: 3s
209:	learn: 0.4149561	total: 967ms	remaining: 2.99s
210:	learn: 0.4147709	total: 972ms	remaining: 2.99s
211:	learn: 0.4146087	total: 976ms	remaining: 2.98s
212:	learn: 0.4144647	total: 981ms	remaining: 2.98s
213:	learn: 0.4142410	total: 985ms	remaining: 2.97s
214:	learn: 0.4140985	total: 989ms	remaining: 2.97s
215:	learn: 0.4139152	total: 993ms	remaining: 2.96s
216:	learn: 0.4137009	total: 998ms	remaining: 2.96s
217:	learn: 0.4133625	total: 1s	remaining: 2.95s
218:	learn: 0.4129461	total: 1s	remaining: 2.94s
219:	learn: 0.4127634	total: 1.01s	remaining: 2.94s
220:	learn: 0.4126676	total: 1.01s	remaining: 2.93s
221:	learn: 0.4123812	total: 1.02s	remaining: 2.93s
222:	learn: 0.4121949	total: 1.02s	remaining: 2.92s
223:	learn: 0.4119210	total: 1.03s	remaining: 2.92s
224:	learn: 0.4116488	total: 1.03s	remaining: 2.91s
225:	learn: 0.4114266	total: 1.03s	remaining: 2.9s
226:	learn: 0.4110627	total: 1.04s	remaining: 2.9s
227:	learn: 0.4107502	total: 1.04s	remaining: 2.89s
228:	learn: 0.4105852	total: 1.05s	remaining: 2.89s
229:	learn: 0.4103124	total: 1.05s	remaining: 2.89s
230:	learn: 0.4100950	total: 1.06s	remaining: 2.88s
231:	learn: 0.4098058	total: 1.06s	remaining: 2.88s
232:	learn: 0.4094825	total: 1.07s	remaining: 2.87s
233:	learn: 0.4092735	total: 1.07s	remaining: 2.87s
234:	learn: 0.4089607	total: 1.07s	remaining: 2.86s
235:	learn: 0.4088336	total: 1.08s	remaining: 2.85s
236:	learn: 0.4086442	total: 1.08s	remaining: 2.85s
237:	learn: 0.4084629	total: 1.09s	remaining: 2.84s
238:	learn: 0.4083745	total: 1.09s	remaining: 2.84s
239:	learn: 0.4081854	total: 1.1s	remaining: 2.83s
240:	learn: 0.4080556	total: 1.1s	remaining: 2.83s
241:	learn: 0.4078128	total: 1.1s	remaining: 2.82s
242:	learn: 0.4075915	total: 1.11s	remaining: 2.81s
243:	learn: 0.4073807	total: 1.11s	remaining: 2.81s
244:	learn: 0.4071171	total: 1.12s	remaining: 2.8s
245:	learn: 0.4067825	total: 1.12s	remaining: 2.8s
246:	learn: 0.4062803	total: 1.13s	remaining: 2.79s
247:	learn: 0.4060433	total: 1.13s	remaining: 2.79s
248:	learn: 0.4057217	total: 1.14s	remaining: 2.79s
249:	learn: 0.4055631	total: 1.14s	remaining: 2.78s
250:	learn: 0.4052949	total: 1.14s	remaining: 2.77s
251:	learn: 0.4052170	total: 1.15s	remaining: 2.77s
252:	learn: 0.4050206	total: 1.15s	remaining: 2.76s
253:	learn: 0.4047839	total: 1.16s	remaining: 2.76s
254:	learn: 0.4045289	total: 1.16s	remaining: 2.75s
255:	learn: 0.4042932	total: 1.17s	remaining: 2.75s
256:	learn: 0.4039444	total: 1.17s	remaining: 2.74s
257:	learn: 0.4036939	total: 1.17s	remaining: 2.74s
258:	learn: 0.4034171	total: 1.18s	remaining: 2.73s
259:	learn: 0.4032002	total: 1.18s	remaining: 2.73s
260:	learn: 0.4030141	total: 1.19s	remaining: 2.72s
261:	learn: 0.4027786	total: 1.19s	remaining: 2.72s
262:	learn: 0.4024916	total: 1.19s	remaining: 2.71s
263:	learn: 0.4022294	total: 1.2s	remaining: 2.71s
264:	learn: 0.4021785	total: 1.2s	remaining: 2.7s
265:	learn: 0.4019230	total: 1.21s	remaining: 2.69s
266:	learn: 0.4016346	total: 1.21s	remaining: 2.69s
267:	learn: 0.4013658	total: 1.22s	remaining: 2.69s
268:	learn: 0.4011382	total: 1.22s	remaining: 2.68s
269:	learn: 0.4010177	total: 1.22s	remaining: 2.67s
270:	learn: 0.4007673	total: 1.23s	remaining: 2.67s
271:	learn: 0.4005666	total: 1.23s	remaining: 2.66s
272:	learn: 0.4002847	total: 1.24s	remaining: 2.66s
273:	learn: 0.4001492	total: 1.24s	remaining: 2.65s
274:	learn: 0.4000321	total: 1.25s	remaining: 2.65s
275:	learn: 0.3999209	total: 1.25s	remaining: 2.64s
276:	learn: 0.3996443	total: 1.25s	remaining: 2.64s
277:	learn: 0.3994722	total: 1.26s	remaining: 2.64s
278:	learn: 0.3991700	total: 1.26s	remaining: 2.63s
279:	learn: 0.3990164	total: 1.27s	remaining: 2.63s
280:	learn: 0.3986838	total: 1.27s	remaining: 2.62s
281:	learn: 0.3984513	total: 1.27s	remaining: 2.61s
282:	learn: 0.3981426	total: 1.28s	remaining: 2.61s
283:	learn: 0.3980179	total: 1.28s	remaining: 2.6s
284:	learn: 0.3977525	total: 1.29s	remaining: 2.6s
285:	learn: 0.3975046	total: 1.29s	remaining: 2.59s
286:	learn: 0.3970873	total: 1.3s	remaining: 2.59s
287:	learn: 0.3966759	total: 1.3s	remaining: 2.58s
288:	learn: 0.3962783	total: 1.3s	remaining: 2.58s
289:	learn: 0.3960555	total: 1.31s	remaining: 2.57s
290:	learn: 0.3958987	total: 1.31s	remaining: 2.57s
291:	learn: 0.3956858	total: 1.32s	remaining: 2.56s
292:	learn: 0.3955401	total: 1.32s	remaining: 2.56s
293:	learn: 0.3952684	total: 1.33s	remaining: 2.55s
294:	learn: 0.3949597	total: 1.33s	remaining: 2.55s
295:	learn: 0.3947830	total: 1.34s	remaining: 2.54s
296:	learn: 0.3945844	total: 1.34s	remaining: 2.54s
297:	learn: 0.3942109	total: 1.34s	remaining: 2.53s
298:	learn: 0.3940289	total: 1.35s	remaining: 2.53s
299:	learn: 0.3937466	total: 1.35s	remaining: 2.52s
300:	learn: 0.3935605	total: 1.36s	remaining: 2.52s
301:	learn: 0.3934678	total: 1.36s	remaining: 2.51s
302:	learn: 0.3932786	total: 1.36s	remaining: 2.51s
303:	learn: 0.3929970	total: 1.37s	remaining: 2.5s
304:	learn: 0.3927124	total: 1.37s	remaining: 2.5s
305:	learn: 0.3924752	total: 1.38s	remaining: 2.49s
306:	learn: 0.3923424	total: 1.38s	remaining: 2.49s
307:	learn: 0.3920411	total: 1.38s	remaining: 2.48s
308:	learn: 0.3918130	total: 1.39s	remaining: 2.48s
309:	learn: 0.3916385	total: 1.39s	remaining: 2.47s
310:	learn: 0.3915032	total: 1.4s	remaining: 2.46s
311:	learn: 0.3911780	total: 1.4s	remaining: 2.46s
312:	learn: 0.3910071	total: 1.4s	remaining: 2.46s
313:	learn: 0.3908706	total: 1.41s	remaining: 2.45s
314:	learn: 0.3907418	total: 1.41s	remaining: 2.44s
315:	learn: 0.3906463	total: 1.42s	remaining: 2.44s
316:	learn: 0.3904210	total: 1.42s	remaining: 2.43s
317:	learn: 0.3901637	total: 1.42s	remaining: 2.43s
318:	learn: 0.3899379	total: 1.43s	remaining: 2.42s
319:	learn: 0.3897595	total: 1.43s	remaining: 2.42s
320:	learn: 0.3894781	total: 1.44s	remaining: 2.41s
321:	learn: 0.3892557	total: 1.44s	remaining: 2.41s
322:	learn: 0.3891618	total: 1.45s	remaining: 2.4s
323:	learn: 0.3890076	total: 1.45s	remaining: 2.4s
324:	learn: 0.3887527	total: 1.46s	remaining: 2.4s
325:	learn: 0.3885953	total: 1.46s	remaining: 2.4s
326:	learn: 0.3884364	total: 1.47s	remaining: 2.39s
327:	learn: 0.3883104	total: 1.47s	remaining: 2.38s
328:	learn: 0.3881895	total: 1.48s	remaining: 2.38s
329:	learn: 0.3879348	total: 1.48s	remaining: 2.38s
330:	learn: 0.3878132	total: 1.48s	remaining: 2.37s
331:	learn: 0.3876204	total: 1.49s	remaining: 2.37s
332:	learn: 0.3873400	total: 1.49s	remaining: 2.36s
333:	learn: 0.3871139	total: 1.5s	remaining: 2.35s
334:	learn: 0.3867589	total: 1.5s	remaining: 2.35s
335:	learn: 0.3864699	total: 1.5s	remaining: 2.35s
336:	learn: 0.3863635	total: 1.51s	remaining: 2.34s
337:	learn: 0.3861522	total: 1.51s	remaining: 2.33s
338:	learn: 0.3858773	total: 1.51s	remaining: 2.33s
339:	learn: 0.3857160	total: 1.52s	remaining: 2.32s
340:	learn: 0.3854085	total: 1.52s	remaining: 2.32s
341:	learn: 0.3852686	total: 1.53s	remaining: 2.31s
342:	learn: 0.3852138	total: 1.53s	remaining: 2.31s
343:	learn: 0.3850657	total: 1.54s	remaining: 2.31s
344:	learn: 0.3849575	total: 1.54s	remaining: 2.3s
345:	learn: 0.3848536	total: 1.54s	remaining: 2.29s
346:	learn: 0.3844597	total: 1.55s	remaining: 2.29s
347:	learn: 0.3843256	total: 1.55s	remaining: 2.28s
348:	learn: 0.3841100	total: 1.56s	remaining: 2.28s
349:	learn: 0.3839055	total: 1.56s	remaining: 2.27s
350:	learn: 0.3837332	total: 1.56s	remaining: 2.27s
351:	learn: 0.3834840	total: 1.57s	remaining: 2.26s
352:	learn: 0.3833479	total: 1.57s	remaining: 2.26s
353:	learn: 0.3833001	total: 1.58s	remaining: 2.25s
354:	learn: 0.3831636	total: 1.58s	remaining: 2.25s
355:	learn: 0.3830058	total: 1.58s	remaining: 2.24s
356:	learn: 0.3827619	total: 1.59s	remaining: 2.24s
357:	learn: 0.3825810	total: 1.59s	remaining: 2.23s
358:	learn: 0.3824705	total: 1.6s	remaining: 2.23s
359:	learn: 0.3821407	total: 1.6s	remaining: 2.22s
360:	learn: 0.3819131	total: 1.6s	remaining: 2.22s
361:	learn: 0.3817345	total: 1.61s	remaining: 2.21s
362:	learn: 0.3815036	total: 1.61s	remaining: 2.21s
363:	learn: 0.3813587	total: 1.62s	remaining: 2.2s
364:	learn: 0.3811200	total: 1.62s	remaining: 2.2s
365:	learn: 0.3810069	total: 1.62s	remaining: 2.19s
366:	learn: 0.3807530	total: 1.63s	remaining: 2.19s
367:	learn: 0.3805037	total: 1.63s	remaining: 2.18s
368:	learn: 0.3801274	total: 1.64s	remaining: 2.18s
369:	learn: 0.3799832	total: 1.64s	remaining: 2.17s
370:	learn: 0.3797605	total: 1.65s	remaining: 2.17s
371:	learn: 0.3795482	total: 1.65s	remaining: 2.17s
372:	learn: 0.3793457	total: 1.66s	remaining: 2.16s
373:	learn: 0.3791410	total: 1.66s	remaining: 2.16s
374:	learn: 0.3790804	total: 1.66s	remaining: 2.15s
375:	learn: 0.3788583	total: 1.67s	remaining: 2.15s
376:	learn: 0.3786833	total: 1.67s	remaining: 2.14s
377:	learn: 0.3785516	total: 1.68s	remaining: 2.14s
378:	learn: 0.3783641	total: 1.68s	remaining: 2.13s
379:	learn: 0.3782124	total: 1.69s	remaining: 2.13s
380:	learn: 0.3781042	total: 1.69s	remaining: 2.12s
381:	learn: 0.3778022	total: 1.69s	remaining: 2.12s
382:	learn: 0.3776258	total: 1.7s	remaining: 2.12s
383:	learn: 0.3773496	total: 1.7s	remaining: 2.11s
384:	learn: 0.3772524	total: 1.71s	remaining: 2.11s
385:	learn: 0.3770613	total: 1.71s	remaining: 2.1s
386:	learn: 0.3769287	total: 1.72s	remaining: 2.1s

VotingClassifier(estimators=[('Model1',
                              Pipeline(steps=[('preprocessor',
                                               ColumnTransformer(transformers=[('num',
                                                                                Pipeline(steps=[('imputer',
                                                                                                 SimpleImputer(strategy='median')),
                                                                                                ('scaler',
                                                                                                 StandardScaler())]),
                                                                                Index(['N_Days', 'Age', 'Bilirubin', 'Cholesterol', 'Albumin', 'Copper',
       'Alk_Phos', 'SGOT', 'Tryglicerides', 'Platelets', 'Prothrombin',
       'Stage'],
      dtype='object...
       'Alk_Phos', 'SGOT', 'Tryglicerides', 'Platelets', 'Prothrombin',
       'Stage'],
      dtype='object')),
                                                                               ('cat',
                                                                                Pipeline(steps=[('imputer',
                                                                                                 SimpleImputer(strategy='most_frequent')),
                                                                                                ('onehot',
                                                                                                 OneHotEncoder(handle_unknown='ignore'))]),
                                                                                Index(['Drug', 'Sex', 'Ascites', 'Hepatomegaly', 'Spiders', 'Edema'], dtype='object'))])),
                                              ('model',
                                               <catboost.core.CatBoostClassifier object at 0x7cdbc0b7a2f0>)]))],
                 voting='soft')

# 📊Generate Predictions and Create Submission File

In [19]:
predict = voting.predict_proba(test)

sub = pd.read_csv('/kaggle/input/playground-series-s3e26/sample_submission.csv')

sub[['Status_C', 'Status_CL', 'Status_D']] = predict

sub.to_csv('sample_submission.csv', index = False)

In [20]:
sub.head()

     id  Status_C  Status_CL  Status_D
0  7905  0.432935   0.034211  0.532854
1  7906  0.457290   0.231730  0.310980
2  7907  0.023223   0.011405  0.965372
3  7908  0.967914   0.003782  0.028304
4  7909  0.872163   0.044636  0.083201